# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160406_0904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('time_period_begin', 'time_period_end', 'product_instance')]),
        ),
    ]
