# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160418_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='dataformat',
            name='slug',
            field=models.CharField(default='slugify', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='slug',
            field=models.CharField(default='slugify', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='slug',
            field=models.CharField(default='slugify', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.CharField(default='slugify', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='grid_resolution_unit',
            field=models.CharField(blank=True, choices=[('m', 'meters'), ('deg', 'degrees')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(default='slugify', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='projection',
            name='slug',
            field=models.CharField(default='slugify', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='servicebackend',
            name='slug',
            field=models.CharField(default='slugify', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='slug',
            field=models.CharField(default='slugify', max_length=255, unique=True),
        ),
    ]
