# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160601_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataformat',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datainstance',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institution',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='license',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projection',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicebackend',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variable',
            name='object_version',
            field=models.IntegerField(default=0),
        ),
    ]
