# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-10 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160901_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainstance',
            name='expires',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
