# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_auto_20160901_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CheckConditionAge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maximum_age', models.IntegerField(verbose_name='Maximum age of the current reference time, in minutes')),
                ('check_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Check')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckConditionDataInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1, verbose_name='Required number of DataInstance objects')),
                ('grace_time', models.IntegerField(default=0, verbose_name='Pass test on less than required number of DataInstance objects for this many minutes, counted from reference time')),
                ('check_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Check')),
                ('format', models.ForeignKey(help_text='Required DataFormat', on_delete=django.db.models.deletion.CASCADE, to='core.DataFormat')),
                ('service_backend', models.ForeignKey(help_text='Required ServiceBackend', on_delete=django.db.models.deletion.CASCADE, to='core.ServiceBackend')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
