# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 08:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkconditiondatainstance',
            name='terms',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Which terms to run this check for, as comma-separated integers'),
        ),
    ]
