# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_checkconditiondatainstance_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='max_severity',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'WARNING'), (2, 'CRITICAL'), (3, 'UNKNOWN')], default=3),
        ),
    ]
