# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-17 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_check_max_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkconditionage',
            name='severity',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'WARNING'), (2, 'CRITICAL'), (3, 'UNKNOWN')], default=2, verbose_name='Minimum severity of check result if sub-check fails'),
        ),
        migrations.AddField(
            model_name='checkconditiondatainstance',
            name='severity',
            field=models.IntegerField(choices=[(0, 'OK'), (1, 'WARNING'), (2, 'CRITICAL'), (3, 'UNKNOWN')], default=2, verbose_name='Minimum severity of check result if sub-check fails'),
        ),
    ]
