# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-29 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20161017_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='pagerduty_service',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='PagerDuty service integration key'),
        ),
    ]
